<?php
/**
 * ConsoleAccessApi
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use HostAfrica\SDK\ApiException;
use HostAfrica\SDK\Configuration;
use HostAfrica\SDK\FormDataProcessor;
use HostAfrica\SDK\HeaderSelector;
use HostAfrica\SDK\ObjectSerializer;

/**
 * ConsoleAccessApi Class Doc Comment
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConsoleAccessApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getNoVncConsole' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getNoVncConsole
     *
     * @param  \HostAfrica\SDK\Model\GetNoVncConsoleRequestContent $get_no_vnc_console_request_content get_no_vnc_console_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNoVncConsole'] to see the possible values for this operation
     *
     * @throws \HostAfrica\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HostAfrica\SDK\Model\GetNoVncConsoleResponseContent|\HostAfrica\SDK\Model\BadRequestErrorResponseContent|\HostAfrica\SDK\Model\UnauthorizedErrorResponseContent|\HostAfrica\SDK\Model\ForbiddenErrorResponseContent|\HostAfrica\SDK\Model\ResourceNotFoundErrorResponseContent|\HostAfrica\SDK\Model\ValidationErrorResponseContent|\HostAfrica\SDK\Model\TooManyRequestsErrorResponseContent|\HostAfrica\SDK\Model\InternalServiceErrorResponseContent|\HostAfrica\SDK\Model\ServiceUnavailableErrorResponseContent
     */
    public function getNoVncConsole($get_no_vnc_console_request_content, string $contentType = self::contentTypes['getNoVncConsole'][0])
    {
        list($response) = $this->getNoVncConsoleWithHttpInfo($get_no_vnc_console_request_content, $contentType);
        return $response;
    }

    /**
     * Operation getNoVncConsoleWithHttpInfo
     *
     * @param  \HostAfrica\SDK\Model\GetNoVncConsoleRequestContent $get_no_vnc_console_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNoVncConsole'] to see the possible values for this operation
     *
     * @throws \HostAfrica\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HostAfrica\SDK\Model\GetNoVncConsoleResponseContent|\HostAfrica\SDK\Model\BadRequestErrorResponseContent|\HostAfrica\SDK\Model\UnauthorizedErrorResponseContent|\HostAfrica\SDK\Model\ForbiddenErrorResponseContent|\HostAfrica\SDK\Model\ResourceNotFoundErrorResponseContent|\HostAfrica\SDK\Model\ValidationErrorResponseContent|\HostAfrica\SDK\Model\TooManyRequestsErrorResponseContent|\HostAfrica\SDK\Model\InternalServiceErrorResponseContent|\HostAfrica\SDK\Model\ServiceUnavailableErrorResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNoVncConsoleWithHttpInfo($get_no_vnc_console_request_content, string $contentType = self::contentTypes['getNoVncConsole'][0])
    {
        $request = $this->getNoVncConsoleRequest($get_no_vnc_console_request_content, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\GetNoVncConsoleResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\BadRequestErrorResponseContent',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\UnauthorizedErrorResponseContent',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\ForbiddenErrorResponseContent',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\ResourceNotFoundErrorResponseContent',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\ValidationErrorResponseContent',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\TooManyRequestsErrorResponseContent',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\InternalServiceErrorResponseContent',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\HostAfrica\SDK\Model\ServiceUnavailableErrorResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HostAfrica\SDK\Model\GetNoVncConsoleResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\GetNoVncConsoleResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\BadRequestErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\UnauthorizedErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\ForbiddenErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\ResourceNotFoundErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\ValidationErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\TooManyRequestsErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\InternalServiceErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HostAfrica\SDK\Model\ServiceUnavailableErrorResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getNoVncConsoleAsync
     *
     * @param  \HostAfrica\SDK\Model\GetNoVncConsoleRequestContent $get_no_vnc_console_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNoVncConsole'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNoVncConsoleAsync($get_no_vnc_console_request_content, string $contentType = self::contentTypes['getNoVncConsole'][0])
    {
        return $this->getNoVncConsoleAsyncWithHttpInfo($get_no_vnc_console_request_content, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNoVncConsoleAsyncWithHttpInfo
     *
     * @param  \HostAfrica\SDK\Model\GetNoVncConsoleRequestContent $get_no_vnc_console_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNoVncConsole'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNoVncConsoleAsyncWithHttpInfo($get_no_vnc_console_request_content, string $contentType = self::contentTypes['getNoVncConsole'][0])
    {
        $returnType = '\HostAfrica\SDK\Model\GetNoVncConsoleResponseContent';
        $request = $this->getNoVncConsoleRequest($get_no_vnc_console_request_content, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNoVncConsole'
     *
     * @param  \HostAfrica\SDK\Model\GetNoVncConsoleRequestContent $get_no_vnc_console_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNoVncConsole'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNoVncConsoleRequest($get_no_vnc_console_request_content, string $contentType = self::contentTypes['getNoVncConsole'][0])
    {

        // verify the required parameter 'get_no_vnc_console_request_content' is set
        if ($get_no_vnc_console_request_content === null || (is_array($get_no_vnc_console_request_content) && count($get_no_vnc_console_request_content) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_no_vnc_console_request_content when calling getNoVncConsole'
            );
        }


        $resourcePath = '/vps/novnc-console';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_no_vnc_console_request_content)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_no_vnc_console_request_content));
            } else {
                $httpBody = $get_no_vnc_console_request_content;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
