<?php
/**
 * ListRdnsResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Model;

use \ArrayAccess;
use \HostAfrica\SDK\ObjectSerializer;

/**
 * ListRdnsResponseData Class Doc Comment
 *
 * @category Class
 * @description Response data for the list-rdns operation
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListRdnsResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListRdnsResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'records' => '\HostAfrica\SDK\Model\RdnsRecord[]',
        'ptr_count' => 'int',
        'ptr_limit' => 'int',
        'custom_ip_mode' => 'bool',
        'subnet_custom_ip_mode' => 'bool',
        'service_only_ips' => 'bool',
        'available_items' => '\HostAfrica\SDK\Model\RdnsAvailableItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'records' => null,
        'ptr_count' => 'int32',
        'ptr_limit' => 'int32',
        'custom_ip_mode' => null,
        'subnet_custom_ip_mode' => null,
        'service_only_ips' => null,
        'available_items' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'records' => false,
        'ptr_count' => false,
        'ptr_limit' => false,
        'custom_ip_mode' => false,
        'subnet_custom_ip_mode' => false,
        'service_only_ips' => false,
        'available_items' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'records' => 'records',
        'ptr_count' => 'ptr_count',
        'ptr_limit' => 'ptr_limit',
        'custom_ip_mode' => 'custom_ip_mode',
        'subnet_custom_ip_mode' => 'subnet_custom_ip_mode',
        'service_only_ips' => 'service_only_ips',
        'available_items' => 'available_items'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'records' => 'setRecords',
        'ptr_count' => 'setPtrCount',
        'ptr_limit' => 'setPtrLimit',
        'custom_ip_mode' => 'setCustomIpMode',
        'subnet_custom_ip_mode' => 'setSubnetCustomIpMode',
        'service_only_ips' => 'setServiceOnlyIps',
        'available_items' => 'setAvailableItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'records' => 'getRecords',
        'ptr_count' => 'getPtrCount',
        'ptr_limit' => 'getPtrLimit',
        'custom_ip_mode' => 'getCustomIpMode',
        'subnet_custom_ip_mode' => 'getSubnetCustomIpMode',
        'service_only_ips' => 'getServiceOnlyIps',
        'available_items' => 'getAvailableItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('records', $data ?? [], null);
        $this->setIfExists('ptr_count', $data ?? [], null);
        $this->setIfExists('ptr_limit', $data ?? [], null);
        $this->setIfExists('custom_ip_mode', $data ?? [], null);
        $this->setIfExists('subnet_custom_ip_mode', $data ?? [], null);
        $this->setIfExists('service_only_ips', $data ?? [], null);
        $this->setIfExists('available_items', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['records'] === null) {
            $invalidProperties[] = "'records' can't be null";
        }
        if ($this->container['ptr_count'] === null) {
            $invalidProperties[] = "'ptr_count' can't be null";
        }
        if ($this->container['ptr_limit'] === null) {
            $invalidProperties[] = "'ptr_limit' can't be null";
        }
        if ($this->container['custom_ip_mode'] === null) {
            $invalidProperties[] = "'custom_ip_mode' can't be null";
        }
        if ($this->container['subnet_custom_ip_mode'] === null) {
            $invalidProperties[] = "'subnet_custom_ip_mode' can't be null";
        }
        if ($this->container['service_only_ips'] === null) {
            $invalidProperties[] = "'service_only_ips' can't be null";
        }
        if ($this->container['available_items'] === null) {
            $invalidProperties[] = "'available_items' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets records
     *
     * @return \HostAfrica\SDK\Model\RdnsRecord[]
     */
    public function getRecords()
    {
        return $this->container['records'];
    }

    /**
     * Sets records
     *
     * @param \HostAfrica\SDK\Model\RdnsRecord[] $records All PTR records owned by the client
     *
     * @return self
     */
    public function setRecords($records)
    {
        if (is_null($records)) {
            throw new \InvalidArgumentException('non-nullable records cannot be null');
        }
        $this->container['records'] = $records;

        return $this;
    }

    /**
     * Gets ptr_count
     *
     * @return int
     */
    public function getPtrCount()
    {
        return $this->container['ptr_count'];
    }

    /**
     * Sets ptr_count
     *
     * @param int $ptr_count Number of PTR records
     *
     * @return self
     */
    public function setPtrCount($ptr_count)
    {
        if (is_null($ptr_count)) {
            throw new \InvalidArgumentException('non-nullable ptr_count cannot be null');
        }
        $this->container['ptr_count'] = $ptr_count;

        return $this;
    }

    /**
     * Gets ptr_limit
     *
     * @return int
     */
    public function getPtrLimit()
    {
        return $this->container['ptr_limit'];
    }

    /**
     * Sets ptr_limit
     *
     * @param int $ptr_limit Lowest finite per-package PTR limit (-1 = unlimited / not configured)
     *
     * @return self
     */
    public function setPtrLimit($ptr_limit)
    {
        if (is_null($ptr_limit)) {
            throw new \InvalidArgumentException('non-nullable ptr_limit cannot be null');
        }
        $this->container['ptr_limit'] = $ptr_limit;

        return $this;
    }

    /**
     * Gets custom_ip_mode
     *
     * @return bool
     */
    public function getCustomIpMode()
    {
        return $this->container['custom_ip_mode'];
    }

    /**
     * Sets custom_ip_mode
     *
     * @param bool $custom_ip_mode Any IP is allowed in the PTR add form
     *
     * @return self
     */
    public function setCustomIpMode($custom_ip_mode)
    {
        if (is_null($custom_ip_mode)) {
            throw new \InvalidArgumentException('non-nullable custom_ip_mode cannot be null');
        }
        $this->container['custom_ip_mode'] = $custom_ip_mode;

        return $this;
    }

    /**
     * Gets subnet_custom_ip_mode
     *
     * @return bool
     */
    public function getSubnetCustomIpMode()
    {
        return $this->container['subnet_custom_ip_mode'];
    }

    /**
     * Sets subnet_custom_ip_mode
     *
     * @param bool $subnet_custom_ip_mode Free-text IP allowed inside an offered subnet pool
     *
     * @return self
     */
    public function setSubnetCustomIpMode($subnet_custom_ip_mode)
    {
        if (is_null($subnet_custom_ip_mode)) {
            throw new \InvalidArgumentException('non-nullable subnet_custom_ip_mode cannot be null');
        }
        $this->container['subnet_custom_ip_mode'] = $subnet_custom_ip_mode;

        return $this;
    }

    /**
     * Gets service_only_ips
     *
     * @return bool
     */
    public function getServiceOnlyIps()
    {
        return $this->container['service_only_ips'];
    }

    /**
     * Sets service_only_ips
     *
     * @param bool $service_only_ips UI hint: only show IPs tied to the related service
     *
     * @return self
     */
    public function setServiceOnlyIps($service_only_ips)
    {
        if (is_null($service_only_ips)) {
            throw new \InvalidArgumentException('non-nullable service_only_ips cannot be null');
        }
        $this->container['service_only_ips'] = $service_only_ips;

        return $this;
    }

    /**
     * Gets available_items
     *
     * @return \HostAfrica\SDK\Model\RdnsAvailableItem[]
     */
    public function getAvailableItems()
    {
        return $this->container['available_items'];
    }

    /**
     * Sets available_items
     *
     * @param \HostAfrica\SDK\Model\RdnsAvailableItem[] $available_items Services the client can manage PTRs for
     *
     * @return self
     */
    public function setAvailableItems($available_items)
    {
        if (is_null($available_items)) {
            throw new \InvalidArgumentException('non-nullable available_items cannot be null');
        }
        $this->container['available_items'] = $available_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


