<?php
/**
 * RdnsAvailableItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Model;

use \ArrayAccess;
use \HostAfrica\SDK\ObjectSerializer;

/**
 * RdnsAvailableItem Class Doc Comment
 *
 * @category Class
 * @description One service the client can manage PTRs for
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RdnsAvailableItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RdnsAvailableItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'int',
        'relid' => 'int',
        'name' => 'string',
        'ips' => 'string[]',
        'pools' => '\HostAfrica\SDK\Model\RdnsPool[]',
        'ptr_limit' => 'int',
        'server_id' => 'int',
        'allow_rdns' => 'bool',
        'rdns_supported' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => 'int32',
        'relid' => 'int32',
        'name' => null,
        'ips' => null,
        'pools' => null,
        'ptr_limit' => 'int32',
        'server_id' => 'int32',
        'allow_rdns' => null,
        'rdns_supported' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'relid' => false,
        'name' => false,
        'ips' => false,
        'pools' => false,
        'ptr_limit' => false,
        'server_id' => false,
        'allow_rdns' => false,
        'rdns_supported' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'relid' => 'relid',
        'name' => 'name',
        'ips' => 'ips',
        'pools' => 'pools',
        'ptr_limit' => 'ptr_limit',
        'server_id' => 'server_id',
        'allow_rdns' => 'allow_rdns',
        'rdns_supported' => 'rdns_supported'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'relid' => 'setRelid',
        'name' => 'setName',
        'ips' => 'setIps',
        'pools' => 'setPools',
        'ptr_limit' => 'setPtrLimit',
        'server_id' => 'setServerId',
        'allow_rdns' => 'setAllowRdns',
        'rdns_supported' => 'setRdnsSupported'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'relid' => 'getRelid',
        'name' => 'getName',
        'ips' => 'getIps',
        'pools' => 'getPools',
        'ptr_limit' => 'getPtrLimit',
        'server_id' => 'getServerId',
        'allow_rdns' => 'getAllowRdns',
        'rdns_supported' => 'getRdnsSupported'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('relid', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('ips', $data ?? [], null);
        $this->setIfExists('pools', $data ?? [], null);
        $this->setIfExists('ptr_limit', $data ?? [], null);
        $this->setIfExists('server_id', $data ?? [], null);
        $this->setIfExists('allow_rdns', $data ?? [], null);
        $this->setIfExists('rdns_supported', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['relid'] === null) {
            $invalidProperties[] = "'relid' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['ips'] === null) {
            $invalidProperties[] = "'ips' can't be null";
        }
        if ($this->container['pools'] === null) {
            $invalidProperties[] = "'pools' can't be null";
        }
        if ($this->container['ptr_limit'] === null) {
            $invalidProperties[] = "'ptr_limit' can't be null";
        }
        if ($this->container['server_id'] === null) {
            $invalidProperties[] = "'server_id' can't be null";
        }
        if ($this->container['allow_rdns'] === null) {
            $invalidProperties[] = "'allow_rdns' can't be null";
        }
        if ($this->container['rdns_supported'] === null) {
            $invalidProperties[] = "'rdns_supported' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return int
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param int $type Zone type matching RdnsRecord.type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets relid
     *
     * @return int
     */
    public function getRelid()
    {
        return $this->container['relid'];
    }

    /**
     * Sets relid
     *
     * @param int $relid Related service identifier
     *
     * @return self
     */
    public function setRelid($relid)
    {
        if (is_null($relid)) {
            throw new \InvalidArgumentException('non-nullable relid cannot be null');
        }
        $this->container['relid'] = $relid;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Display label for the service
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets ips
     *
     * @return string[]
     */
    public function getIps()
    {
        return $this->container['ips'];
    }

    /**
     * Sets ips
     *
     * @param string[] $ips Concrete IP addresses available for this service
     *
     * @return self
     */
    public function setIps($ips)
    {
        if (is_null($ips)) {
            throw new \InvalidArgumentException('non-nullable ips cannot be null');
        }
        $this->container['ips'] = $ips;

        return $this;
    }

    /**
     * Gets pools
     *
     * @return \HostAfrica\SDK\Model\RdnsPool[]
     */
    public function getPools()
    {
        return $this->container['pools'];
    }

    /**
     * Sets pools
     *
     * @param \HostAfrica\SDK\Model\RdnsPool[] $pools Subnet pools available when subnet_custom_ip_mode is on
     *
     * @return self
     */
    public function setPools($pools)
    {
        if (is_null($pools)) {
            throw new \InvalidArgumentException('non-nullable pools cannot be null');
        }
        $this->container['pools'] = $pools;

        return $this;
    }

    /**
     * Gets ptr_limit
     *
     * @return int
     */
    public function getPtrLimit()
    {
        return $this->container['ptr_limit'];
    }

    /**
     * Sets ptr_limit
     *
     * @param int $ptr_limit Per-package PTR limit (-1 = unlimited)
     *
     * @return self
     */
    public function setPtrLimit($ptr_limit)
    {
        if (is_null($ptr_limit)) {
            throw new \InvalidArgumentException('non-nullable ptr_limit cannot be null');
        }
        $this->container['ptr_limit'] = $ptr_limit;

        return $this;
    }

    /**
     * Gets server_id
     *
     * @return int
     */
    public function getServerId()
    {
        return $this->container['server_id'];
    }

    /**
     * Sets server_id
     *
     * @param int $server_id server_id
     *
     * @return self
     */
    public function setServerId($server_id)
    {
        if (is_null($server_id)) {
            throw new \InvalidArgumentException('non-nullable server_id cannot be null');
        }
        $this->container['server_id'] = $server_id;

        return $this;
    }

    /**
     * Gets allow_rdns
     *
     * @return bool
     */
    public function getAllowRdns()
    {
        return $this->container['allow_rdns'];
    }

    /**
     * Sets allow_rdns
     *
     * @param bool $allow_rdns Server has ALLOW_RDNS=on
     *
     * @return self
     */
    public function setAllowRdns($allow_rdns)
    {
        if (is_null($allow_rdns)) {
            throw new \InvalidArgumentException('non-nullable allow_rdns cannot be null');
        }
        $this->container['allow_rdns'] = $allow_rdns;

        return $this;
    }

    /**
     * Gets rdns_supported
     *
     * @return bool
     */
    public function getRdnsSupported()
    {
        return $this->container['rdns_supported'];
    }

    /**
     * Sets rdns_supported
     *
     * @param bool $rdns_supported Server module supports rDNS
     *
     * @return self
     */
    public function setRdnsSupported($rdns_supported)
    {
        if (is_null($rdns_supported)) {
            throw new \InvalidArgumentException('non-nullable rdns_supported cannot be null');
        }
        $this->container['rdns_supported'] = $rdns_supported;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


