<?php
/**
 * ServiceBackupsResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Model;

use \ArrayAccess;
use \HostAfrica\SDK\ObjectSerializer;

/**
 * ServiceBackupsResponseData Class Doc Comment
 *
 * @category Class
 * @description Response data for service backups operation
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceBackupsResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceBackupsResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'message' => 'string',
        'backups' => '\HostAfrica\SDK\Model\BackupItem[]',
        'quota_total' => 'float',
        'quota_used' => 'float',
        'quota_unit' => 'string',
        'available_compress_methods' => '\HostAfrica\SDK\Model\CompressionMethod[]',
        'available_modes' => '\HostAfrica\SDK\Model\BackupMode[]',
        'backup_is_creating' => 'bool',
        'backup_creation' => '\HostAfrica\SDK\Model\BackupCreationInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'message' => null,
        'backups' => null,
        'quota_total' => 'double',
        'quota_used' => 'double',
        'quota_unit' => null,
        'available_compress_methods' => null,
        'available_modes' => null,
        'backup_is_creating' => null,
        'backup_creation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'message' => false,
        'backups' => false,
        'quota_total' => false,
        'quota_used' => false,
        'quota_unit' => false,
        'available_compress_methods' => false,
        'available_modes' => false,
        'backup_is_creating' => false,
        'backup_creation' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'message' => 'message',
        'backups' => 'backups',
        'quota_total' => 'quota_total',
        'quota_used' => 'quota_used',
        'quota_unit' => 'quota_unit',
        'available_compress_methods' => 'available_compress_methods',
        'available_modes' => 'available_modes',
        'backup_is_creating' => 'backup_is_creating',
        'backup_creation' => 'backup_creation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'message' => 'setMessage',
        'backups' => 'setBackups',
        'quota_total' => 'setQuotaTotal',
        'quota_used' => 'setQuotaUsed',
        'quota_unit' => 'setQuotaUnit',
        'available_compress_methods' => 'setAvailableCompressMethods',
        'available_modes' => 'setAvailableModes',
        'backup_is_creating' => 'setBackupIsCreating',
        'backup_creation' => 'setBackupCreation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'message' => 'getMessage',
        'backups' => 'getBackups',
        'quota_total' => 'getQuotaTotal',
        'quota_used' => 'getQuotaUsed',
        'quota_unit' => 'getQuotaUnit',
        'available_compress_methods' => 'getAvailableCompressMethods',
        'available_modes' => 'getAvailableModes',
        'backup_is_creating' => 'getBackupIsCreating',
        'backup_creation' => 'getBackupCreation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('backups', $data ?? [], null);
        $this->setIfExists('quota_total', $data ?? [], null);
        $this->setIfExists('quota_used', $data ?? [], null);
        $this->setIfExists('quota_unit', $data ?? [], null);
        $this->setIfExists('available_compress_methods', $data ?? [], null);
        $this->setIfExists('available_modes', $data ?? [], null);
        $this->setIfExists('backup_is_creating', $data ?? [], null);
        $this->setIfExists('backup_creation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ($this->container['backups'] === null) {
            $invalidProperties[] = "'backups' can't be null";
        }
        if ($this->container['quota_used'] === null) {
            $invalidProperties[] = "'quota_used' can't be null";
        }
        if ($this->container['quota_unit'] === null) {
            $invalidProperties[] = "'quota_unit' can't be null";
        }
        if ($this->container['available_compress_methods'] === null) {
            $invalidProperties[] = "'available_compress_methods' can't be null";
        }
        if ($this->container['available_modes'] === null) {
            $invalidProperties[] = "'available_modes' can't be null";
        }
        if ($this->container['backup_is_creating'] === null) {
            $invalidProperties[] = "'backup_is_creating' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message Status message indicating the result
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets backups
     *
     * @return \HostAfrica\SDK\Model\BackupItem[]
     */
    public function getBackups()
    {
        return $this->container['backups'];
    }

    /**
     * Sets backups
     *
     * @param \HostAfrica\SDK\Model\BackupItem[] $backups List of backups for the service
     *
     * @return self
     */
    public function setBackups($backups)
    {
        if (is_null($backups)) {
            throw new \InvalidArgumentException('non-nullable backups cannot be null');
        }
        $this->container['backups'] = $backups;

        return $this;
    }

    /**
     * Gets quota_total
     *
     * @return float|null
     */
    public function getQuotaTotal()
    {
        return $this->container['quota_total'];
    }

    /**
     * Sets quota_total
     *
     * @param float|null $quota_total Total backup quota (null if unlimited)
     *
     * @return self
     */
    public function setQuotaTotal($quota_total)
    {
        if (is_null($quota_total)) {
            throw new \InvalidArgumentException('non-nullable quota_total cannot be null');
        }
        $this->container['quota_total'] = $quota_total;

        return $this;
    }

    /**
     * Gets quota_used
     *
     * @return float
     */
    public function getQuotaUsed()
    {
        return $this->container['quota_used'];
    }

    /**
     * Sets quota_used
     *
     * @param float $quota_used Used backup quota
     *
     * @return self
     */
    public function setQuotaUsed($quota_used)
    {
        if (is_null($quota_used)) {
            throw new \InvalidArgumentException('non-nullable quota_used cannot be null');
        }
        $this->container['quota_used'] = $quota_used;

        return $this;
    }

    /**
     * Gets quota_unit
     *
     * @return string
     */
    public function getQuotaUnit()
    {
        return $this->container['quota_unit'];
    }

    /**
     * Sets quota_unit
     *
     * @param string $quota_unit Unit for quota measurements (e.g., GiB)
     *
     * @return self
     */
    public function setQuotaUnit($quota_unit)
    {
        if (is_null($quota_unit)) {
            throw new \InvalidArgumentException('non-nullable quota_unit cannot be null');
        }
        $this->container['quota_unit'] = $quota_unit;

        return $this;
    }

    /**
     * Gets available_compress_methods
     *
     * @return \HostAfrica\SDK\Model\CompressionMethod[]
     */
    public function getAvailableCompressMethods()
    {
        return $this->container['available_compress_methods'];
    }

    /**
     * Sets available_compress_methods
     *
     * @param \HostAfrica\SDK\Model\CompressionMethod[] $available_compress_methods Available compression methods for creating backups
     *
     * @return self
     */
    public function setAvailableCompressMethods($available_compress_methods)
    {
        if (is_null($available_compress_methods)) {
            throw new \InvalidArgumentException('non-nullable available_compress_methods cannot be null');
        }
        $this->container['available_compress_methods'] = $available_compress_methods;

        return $this;
    }

    /**
     * Gets available_modes
     *
     * @return \HostAfrica\SDK\Model\BackupMode[]
     */
    public function getAvailableModes()
    {
        return $this->container['available_modes'];
    }

    /**
     * Sets available_modes
     *
     * @param \HostAfrica\SDK\Model\BackupMode[] $available_modes Available backup modes
     *
     * @return self
     */
    public function setAvailableModes($available_modes)
    {
        if (is_null($available_modes)) {
            throw new \InvalidArgumentException('non-nullable available_modes cannot be null');
        }
        $this->container['available_modes'] = $available_modes;

        return $this;
    }

    /**
     * Gets backup_is_creating
     *
     * @return bool
     */
    public function getBackupIsCreating()
    {
        return $this->container['backup_is_creating'];
    }

    /**
     * Sets backup_is_creating
     *
     * @param bool $backup_is_creating Whether a backup is currently being created
     *
     * @return self
     */
    public function setBackupIsCreating($backup_is_creating)
    {
        if (is_null($backup_is_creating)) {
            throw new \InvalidArgumentException('non-nullable backup_is_creating cannot be null');
        }
        $this->container['backup_is_creating'] = $backup_is_creating;

        return $this;
    }

    /**
     * Gets backup_creation
     *
     * @return \HostAfrica\SDK\Model\BackupCreationInfo|null
     */
    public function getBackupCreation()
    {
        return $this->container['backup_creation'];
    }

    /**
     * Sets backup_creation
     *
     * @param \HostAfrica\SDK\Model\BackupCreationInfo|null $backup_creation backup_creation
     *
     * @return self
     */
    public function setBackupCreation($backup_creation)
    {
        if (is_null($backup_creation)) {
            throw new \InvalidArgumentException('non-nullable backup_creation cannot be null');
        }
        $this->container['backup_creation'] = $backup_creation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


