<?php
/**
 * UpdatePowerTaskRequestContent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Model;

use \ArrayAccess;
use \HostAfrica\SDK\ObjectSerializer;

/**
 * UpdatePowerTaskRequestContent Class Doc Comment
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdatePowerTaskRequestContent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdatePowerTaskRequestContent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'service_id' => 'string',
        'task_id' => 'int',
        'power_task_action' => 'string',
        'start_date' => 'string',
        'description' => 'string',
        'start_time' => 'string',
        'end_date' => 'string',
        'end_time' => 'string',
        'job_type' => '\HostAfrica\SDK\Model\PowerTaskJobType',
        'job_time' => 'string',
        'job_hour' => 'int',
        'job_minutes' => 'int',
        'days' => '\HostAfrica\SDK\Model\DayOfWeek[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'service_id' => null,
        'task_id' => 'int32',
        'power_task_action' => null,
        'start_date' => null,
        'description' => null,
        'start_time' => null,
        'end_date' => null,
        'end_time' => null,
        'job_type' => null,
        'job_time' => null,
        'job_hour' => 'int32',
        'job_minutes' => 'int32',
        'days' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'service_id' => false,
        'task_id' => false,
        'power_task_action' => false,
        'start_date' => false,
        'description' => false,
        'start_time' => false,
        'end_date' => false,
        'end_time' => false,
        'job_type' => false,
        'job_time' => false,
        'job_hour' => false,
        'job_minutes' => false,
        'days' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'service_id' => 'service_id',
        'task_id' => 'task_id',
        'power_task_action' => 'power_task_action',
        'start_date' => 'start_date',
        'description' => 'description',
        'start_time' => 'start_time',
        'end_date' => 'end_date',
        'end_time' => 'end_time',
        'job_type' => 'job_type',
        'job_time' => 'job_time',
        'job_hour' => 'job_hour',
        'job_minutes' => 'job_minutes',
        'days' => 'days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'service_id' => 'setServiceId',
        'task_id' => 'setTaskId',
        'power_task_action' => 'setPowerTaskAction',
        'start_date' => 'setStartDate',
        'description' => 'setDescription',
        'start_time' => 'setStartTime',
        'end_date' => 'setEndDate',
        'end_time' => 'setEndTime',
        'job_type' => 'setJobType',
        'job_time' => 'setJobTime',
        'job_hour' => 'setJobHour',
        'job_minutes' => 'setJobMinutes',
        'days' => 'setDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'service_id' => 'getServiceId',
        'task_id' => 'getTaskId',
        'power_task_action' => 'getPowerTaskAction',
        'start_date' => 'getStartDate',
        'description' => 'getDescription',
        'start_time' => 'getStartTime',
        'end_date' => 'getEndDate',
        'end_time' => 'getEndTime',
        'job_type' => 'getJobType',
        'job_time' => 'getJobTime',
        'job_hour' => 'getJobHour',
        'job_minutes' => 'getJobMinutes',
        'days' => 'getDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('task_id', $data ?? [], null);
        $this->setIfExists('power_task_action', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('job_type', $data ?? [], null);
        $this->setIfExists('job_time', $data ?? [], null);
        $this->setIfExists('job_hour', $data ?? [], null);
        $this->setIfExists('job_minutes', $data ?? [], null);
        $this->setIfExists('days', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['service_id'] === null) {
            $invalidProperties[] = "'service_id' can't be null";
        }
        if ($this->container['task_id'] === null) {
            $invalidProperties[] = "'task_id' can't be null";
        }
        if (!is_null($this->container['start_date']) && !preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", $this->container['start_date'])) {
            $invalidProperties[] = "invalid value for 'start_date', must be conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.";
        }

        if (!is_null($this->container['start_time']) && !preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", $this->container['start_time'])) {
            $invalidProperties[] = "invalid value for 'start_time', must be conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.";
        }

        if (!is_null($this->container['end_date']) && !preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", $this->container['end_date'])) {
            $invalidProperties[] = "invalid value for 'end_date', must be conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.";
        }

        if (!is_null($this->container['end_time']) && !preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", $this->container['end_time'])) {
            $invalidProperties[] = "invalid value for 'end_time', must be conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.";
        }

        if (!is_null($this->container['job_time']) && !preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", $this->container['job_time'])) {
            $invalidProperties[] = "invalid value for 'job_time', must be conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.";
        }

        if (!is_null($this->container['job_hour']) && ($this->container['job_hour'] > 23)) {
            $invalidProperties[] = "invalid value for 'job_hour', must be smaller than or equal to 23.";
        }

        if (!is_null($this->container['job_hour']) && ($this->container['job_hour'] < 0)) {
            $invalidProperties[] = "invalid value for 'job_hour', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['job_minutes']) && ($this->container['job_minutes'] > 59)) {
            $invalidProperties[] = "invalid value for 'job_minutes', must be smaller than or equal to 59.";
        }

        if (!is_null($this->container['job_minutes']) && ($this->container['job_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'job_minutes', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets service_id
     *
     * @return string
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param string $service_id Service ID - must be sent as a string
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            throw new \InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets task_id
     *
     * @return int
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     *
     * @param int $task_id Power task ID to update
     *
     * @return self
     */
    public function setTaskId($task_id)
    {
        if (is_null($task_id)) {
            throw new \InvalidArgumentException('non-nullable task_id cannot be null');
        }
        $this->container['task_id'] = $task_id;

        return $this;
    }

    /**
     * Gets power_task_action
     *
     * @return string|null
     */
    public function getPowerTaskAction()
    {
        return $this->container['power_task_action'];
    }

    /**
     * Sets power_task_action
     *
     * @param string|null $power_task_action Power action to perform (start, stop, restart)
     *
     * @return self
     */
    public function setPowerTaskAction($power_task_action)
    {
        if (is_null($power_task_action)) {
            throw new \InvalidArgumentException('non-nullable power_task_action cannot be null');
        }
        $this->container['power_task_action'] = $power_task_action;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return string|null
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param string|null $start_date Start date in Y-m-d format (e.g., 2026-03-25)
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            throw new \InvalidArgumentException('non-nullable start_date cannot be null');
        }

        if ((!preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", ObjectSerializer::toString($start_date)))) {
            throw new \InvalidArgumentException("invalid value for \$start_date when calling UpdatePowerTaskRequestContent., must conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.");
        }

        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description of the power task
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return string|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param string|null $start_time Start time in HH:MM or HH:MM:SS format
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }

        if ((!preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", ObjectSerializer::toString($start_time)))) {
            throw new \InvalidArgumentException("invalid value for \$start_time when calling UpdatePowerTaskRequestContent., must conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.");
        }

        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return string|null
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param string|null $end_date End date in Y-m-d format (e.g., 2026-12-31)
     *
     * @return self
     */
    public function setEndDate($end_date)
    {
        if (is_null($end_date)) {
            throw new \InvalidArgumentException('non-nullable end_date cannot be null');
        }

        if ((!preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", ObjectSerializer::toString($end_date)))) {
            throw new \InvalidArgumentException("invalid value for \$end_date when calling UpdatePowerTaskRequestContent., must conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.");
        }

        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return string|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param string|null $end_time End time in HH:MM or HH:MM:SS format
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            throw new \InvalidArgumentException('non-nullable end_time cannot be null');
        }

        if ((!preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", ObjectSerializer::toString($end_time)))) {
            throw new \InvalidArgumentException("invalid value for \$end_time when calling UpdatePowerTaskRequestContent., must conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.");
        }

        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets job_type
     *
     * @return \HostAfrica\SDK\Model\PowerTaskJobType|null
     */
    public function getJobType()
    {
        return $this->container['job_type'];
    }

    /**
     * Sets job_type
     *
     * @param \HostAfrica\SDK\Model\PowerTaskJobType|null $job_type job_type
     *
     * @return self
     */
    public function setJobType($job_type)
    {
        if (is_null($job_type)) {
            throw new \InvalidArgumentException('non-nullable job_type cannot be null');
        }
        $this->container['job_type'] = $job_type;

        return $this;
    }

    /**
     * Gets job_time
     *
     * @return string|null
     */
    public function getJobTime()
    {
        return $this->container['job_time'];
    }

    /**
     * Sets job_time
     *
     * @param string|null $job_time Job execution time in HH:MM or HH:MM:SS format
     *
     * @return self
     */
    public function setJobTime($job_time)
    {
        if (is_null($job_time)) {
            throw new \InvalidArgumentException('non-nullable job_time cannot be null');
        }

        if ((!preg_match("/^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/", ObjectSerializer::toString($job_time)))) {
            throw new \InvalidArgumentException("invalid value for \$job_time when calling UpdatePowerTaskRequestContent., must conform to the pattern /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/.");
        }

        $this->container['job_time'] = $job_time;

        return $this;
    }

    /**
     * Gets job_hour
     *
     * @return int|null
     */
    public function getJobHour()
    {
        return $this->container['job_hour'];
    }

    /**
     * Sets job_hour
     *
     * @param int|null $job_hour Job hour (alternative to job_time)
     *
     * @return self
     */
    public function setJobHour($job_hour)
    {
        if (is_null($job_hour)) {
            throw new \InvalidArgumentException('non-nullable job_hour cannot be null');
        }

        if (($job_hour > 23)) {
            throw new \InvalidArgumentException('invalid value for $job_hour when calling UpdatePowerTaskRequestContent., must be smaller than or equal to 23.');
        }
        if (($job_hour < 0)) {
            throw new \InvalidArgumentException('invalid value for $job_hour when calling UpdatePowerTaskRequestContent., must be bigger than or equal to 0.');
        }

        $this->container['job_hour'] = $job_hour;

        return $this;
    }

    /**
     * Gets job_minutes
     *
     * @return int|null
     */
    public function getJobMinutes()
    {
        return $this->container['job_minutes'];
    }

    /**
     * Sets job_minutes
     *
     * @param int|null $job_minutes Job minutes (alternative to job_time)
     *
     * @return self
     */
    public function setJobMinutes($job_minutes)
    {
        if (is_null($job_minutes)) {
            throw new \InvalidArgumentException('non-nullable job_minutes cannot be null');
        }

        if (($job_minutes > 59)) {
            throw new \InvalidArgumentException('invalid value for $job_minutes when calling UpdatePowerTaskRequestContent., must be smaller than or equal to 59.');
        }
        if (($job_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $job_minutes when calling UpdatePowerTaskRequestContent., must be bigger than or equal to 0.');
        }

        $this->container['job_minutes'] = $job_minutes;

        return $this;
    }

    /**
     * Gets days
     *
     * @return \HostAfrica\SDK\Model\DayOfWeek[]|null
     */
    public function getDays()
    {
        return $this->container['days'];
    }

    /**
     * Sets days
     *
     * @param \HostAfrica\SDK\Model\DayOfWeek[]|null $days Days of the week for weekly jobs
     *
     * @return self
     */
    public function setDays($days)
    {
        if (is_null($days)) {
            throw new \InvalidArgumentException('non-nullable days cannot be null');
        }
        $this->container['days'] = $days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


