<?php
/**
 * VpsBandwidthInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HostAfrica\SDK\Model;

use \ArrayAccess;
use \HostAfrica\SDK\ObjectSerializer;

/**
 * VpsBandwidthInfo Class Doc Comment
 *
 * @category Class
 * @description Bandwidth usage information
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VpsBandwidthInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VpsBandwidthInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'usage_mb' => 'float',
        'limit_mb' => 'float',
        'unlimited' => 'bool',
        'percent' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'usage_mb' => 'double',
        'limit_mb' => 'double',
        'unlimited' => null,
        'percent' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'usage_mb' => false,
        'limit_mb' => false,
        'unlimited' => false,
        'percent' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'usage_mb' => 'usage_mb',
        'limit_mb' => 'limit_mb',
        'unlimited' => 'unlimited',
        'percent' => 'percent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'usage_mb' => 'setUsageMb',
        'limit_mb' => 'setLimitMb',
        'unlimited' => 'setUnlimited',
        'percent' => 'setPercent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'usage_mb' => 'getUsageMb',
        'limit_mb' => 'getLimitMb',
        'unlimited' => 'getUnlimited',
        'percent' => 'getPercent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('usage_mb', $data ?? [], null);
        $this->setIfExists('limit_mb', $data ?? [], null);
        $this->setIfExists('unlimited', $data ?? [], null);
        $this->setIfExists('percent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['usage_mb']) && ($this->container['usage_mb'] < 0)) {
            $invalidProperties[] = "invalid value for 'usage_mb', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['limit_mb']) && ($this->container['limit_mb'] < 0)) {
            $invalidProperties[] = "invalid value for 'limit_mb', must be bigger than or equal to 0.";
        }

        if ($this->container['unlimited'] === null) {
            $invalidProperties[] = "'unlimited' can't be null";
        }
        if (!is_null($this->container['percent']) && ($this->container['percent'] > 100)) {
            $invalidProperties[] = "invalid value for 'percent', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['percent']) && ($this->container['percent'] < 0)) {
            $invalidProperties[] = "invalid value for 'percent', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets usage_mb
     *
     * @return float|null
     */
    public function getUsageMb()
    {
        return $this->container['usage_mb'];
    }

    /**
     * Sets usage_mb
     *
     * @param float|null $usage_mb Bandwidth usage in MB
     *
     * @return self
     */
    public function setUsageMb($usage_mb)
    {
        if (is_null($usage_mb)) {
            throw new \InvalidArgumentException('non-nullable usage_mb cannot be null');
        }

        if (($usage_mb < 0)) {
            throw new \InvalidArgumentException('invalid value for $usage_mb when calling VpsBandwidthInfo., must be bigger than or equal to 0.');
        }

        $this->container['usage_mb'] = $usage_mb;

        return $this;
    }

    /**
     * Gets limit_mb
     *
     * @return float|null
     */
    public function getLimitMb()
    {
        return $this->container['limit_mb'];
    }

    /**
     * Sets limit_mb
     *
     * @param float|null $limit_mb Bandwidth limit in MB
     *
     * @return self
     */
    public function setLimitMb($limit_mb)
    {
        if (is_null($limit_mb)) {
            throw new \InvalidArgumentException('non-nullable limit_mb cannot be null');
        }

        if (($limit_mb < 0)) {
            throw new \InvalidArgumentException('invalid value for $limit_mb when calling VpsBandwidthInfo., must be bigger than or equal to 0.');
        }

        $this->container['limit_mb'] = $limit_mb;

        return $this;
    }

    /**
     * Gets unlimited
     *
     * @return bool
     */
    public function getUnlimited()
    {
        return $this->container['unlimited'];
    }

    /**
     * Sets unlimited
     *
     * @param bool $unlimited Whether bandwidth is unlimited
     *
     * @return self
     */
    public function setUnlimited($unlimited)
    {
        if (is_null($unlimited)) {
            throw new \InvalidArgumentException('non-nullable unlimited cannot be null');
        }
        $this->container['unlimited'] = $unlimited;

        return $this;
    }

    /**
     * Gets percent
     *
     * @return float|null
     */
    public function getPercent()
    {
        return $this->container['percent'];
    }

    /**
     * Sets percent
     *
     * @param float|null $percent Bandwidth usage percentage
     *
     * @return self
     */
    public function setPercent($percent)
    {
        if (is_null($percent)) {
            throw new \InvalidArgumentException('non-nullable percent cannot be null');
        }

        if (($percent > 100)) {
            throw new \InvalidArgumentException('invalid value for $percent when calling VpsBandwidthInfo., must be smaller than or equal to 100.');
        }
        if (($percent < 0)) {
            throw new \InvalidArgumentException('invalid value for $percent when calling VpsBandwidthInfo., must be bigger than or equal to 0.');
        }

        $this->container['percent'] = $percent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


