<?php
/**
 * NoVncConsoleResponseDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * NoVncConsoleResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description Response data for noVNC console operation
 * @package     HostAfrica\\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NoVncConsoleResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "NoVncConsoleResponseData"
     */
    public function testNoVncConsoleResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "console"
     */
    public function testPropertyConsole()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
