<?php
/**
 * RdnsAvailableItemTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RdnsAvailableItemTest Class Doc Comment
 *
 * @category    Class
 * @description One service the client can manage PTRs for
 * @package     HostAfrica\\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RdnsAvailableItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RdnsAvailableItem"
     */
    public function testRdnsAvailableItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relid"
     */
    public function testPropertyRelid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ips"
     */
    public function testPropertyIps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pools"
     */
    public function testPropertyPools()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ptr_limit"
     */
    public function testPropertyPtrLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "server_id"
     */
    public function testPropertyServerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_rdns"
     */
    public function testPropertyAllowRdns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rdns_supported"
     */
    public function testPropertyRdnsSupported()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
