<?php
/**
 * ServiceBackupsResponseDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServiceBackupsResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description Response data for service backups operation
 * @package     HostAfrica\\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServiceBackupsResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceBackupsResponseData"
     */
    public function testServiceBackupsResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backups"
     */
    public function testPropertyBackups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quota_total"
     */
    public function testPropertyQuotaTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quota_used"
     */
    public function testPropertyQuotaUsed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quota_unit"
     */
    public function testPropertyQuotaUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "available_compress_methods"
     */
    public function testPropertyAvailableCompressMethods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "available_modes"
     */
    public function testPropertyAvailableModes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup_is_creating"
     */
    public function testPropertyBackupIsCreating()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup_creation"
     */
    public function testPropertyBackupCreation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
