<?php
/**
 * UpdateFirewallRuleRequestContentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateFirewallRuleRequestContentTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateFirewallRuleRequestContent
 * @package     HostAfrica\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateFirewallRuleRequestContentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateFirewallRuleRequestContent"
     */
    public function testUpdateFirewallRuleRequestContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pos"
     */
    public function testPropertyPos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rule_action"
     */
    public function testPropertyRuleAction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
