<?php
/**
 * VpsAvailableFeaturesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VpsAvailableFeaturesTest Class Doc Comment
 *
 * @category    Class
 * @description Available features for the VPS
 * @package     HostAfrica\\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VpsAvailableFeaturesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VpsAvailableFeatures"
     */
    public function testVpsAvailableFeatures()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "power_start"
     */
    public function testPropertyPowerStart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "power_stop"
     */
    public function testPropertyPowerStop()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "power_reboot"
     */
    public function testPropertyPowerReboot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "power_shutdown"
     */
    public function testPropertyPowerShutdown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "novnc_console"
     */
    public function testPropertyNovncConsole()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backups"
     */
    public function testPropertyBackups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup_jobs"
     */
    public function testPropertyBackupJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup_schedule"
     */
    public function testPropertyBackupSchedule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "firewall"
     */
    public function testPropertyFirewall()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reinstall"
     */
    public function testPropertyReinstall()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "change_hostname"
     */
    public function testPropertyChangeHostname()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "change_iso_image"
     */
    public function testPropertyChangeIsoImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "network_stats"
     */
    public function testPropertyNetworkStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "graphs"
     */
    public function testPropertyGraphs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "os_templates"
     */
    public function testPropertyOsTemplates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
