<?php
/**
 * VpsBandwidthInfoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HostAfrica\\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VpsBandwidthInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Bandwidth usage information
 * @package     HostAfrica\\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VpsBandwidthInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VpsBandwidthInfo"
     */
    public function testVpsBandwidthInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "usage_mb"
     */
    public function testPropertyUsageMb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "limit_mb"
     */
    public function testPropertyLimitMb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unlimited"
     */
    public function testPropertyUnlimited()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "percent"
     */
    public function testPropertyPercent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
