<?php
/**
 * DomainsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace HostAfrica\SDK\Test\Api;

use \HostAfrica\SDK\Configuration;
use \HostAfrica\SDK\ApiException;
use \HostAfrica\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DomainsApiTest Class Doc Comment
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkDomainAvailability
     *
     * .
     *
     */
    public function testCheckDomainAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDomain
     *
     * .
     *
     */
    public function testGetDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDomainContacts
     *
     * .
     *
     */
    public function testGetDomainContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDomains
     *
     * .
     *
     */
    public function testListDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDomainsRequiringData
     *
     * .
     *
     */
    public function testListDomainsRequiringData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveDomainRequiredData
     *
     * .
     *
     */
    public function testSaveDomainRequiredData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for suggestDomains
     *
     * .
     *
     */
    public function testSuggestDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDomainSettings
     *
     * .
     *
     */
    public function testUpdateDomainSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
