<?php
/**
 * SnapshotsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HostAfricaApi
 *
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace HostAfrica\SDK\Test\Api;

use \HostAfrica\SDK\Configuration;
use \HostAfrica\SDK\ApiException;
use \HostAfrica\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SnapshotsApiTest Class Doc Comment
 *
 * @category Class
 * @package  HostAfrica\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SnapshotsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSnapshot
     *
     * .
     *
     */
    public function testCreateSnapshot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSnapshot
     *
     * .
     *
     */
    public function testDeleteSnapshot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSnapshots
     *
     * .
     *
     */
    public function testListSnapshots()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rollbackSnapshot
     *
     * .
     *
     */
    public function testRollbackSnapshot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSnapshot
     *
     * .
     *
     */
    public function testUpdateSnapshot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
